* TODO show set rules
show set rules: apply the style to existing elements
This probably requires evalStyles to be a Map Identifier (Map Identifier Val)
and go directly to fields.
But for this we need to know how to populate fields from positional.
This info is in the modules.
If we do this we cn also remove the kludgy Semigroup instance for Arguments.
* TODO label and ref
label-02
label-03
label-04
label-05
label-06
ref-04
ref-03, 05 element method
* TODO locate and query - SKIP instead of error?
#set page(header: locate(loc => {
  let elems = query(
    selector(heading).before(loc),
    loc,
  )
  let academy = smallcaps[
    Typst Academy
  ]
  if elems == () {
    align(right, academy)
  } else {
    let body = elems.last().body
    academy + h(1fr) + emph(body)
  }
}))
* small test issues
** meta
counter-00, 01, etc. (we don't support counter objects)
figure-02 (counter)
state-00, 01 (state object)
** compute
data - all these are failing due to paths - what is "/bad.txt"?
repeat function needs to be implemented
** compiler
content-field-00
import-10,11 - check for cyclic import
ops-03
ops-11
show-bare-00 (columns.with(2)?)
show-node-08 : '#show text: none' should affect text
show-selector-01 (just needs show set to be implemented)
show-test-06
spread-10
while-03 (develop detection of infinite loop?)
** less worrisome:
We have preliminary support but not complete:
matrix-alignment-00 (need to split on & and make cells?)
matrix-alignment-01 (see above)

 return still isn't right inside content blocks return-03 return-05 return-06

closure-09 (this is an edge issue which we could address by assigning default values to params before assigning params, but that adds complexity)
color-00 (negate)
color-01 (lighten)
break-continue-10 (#break inside a text block instead of a code block, not currently supported)
break-continue-11 (break in set rule...not supported but not crucial)
* TODO improve output for undergraduate.typ
- column flow:
  use css "columns: 2" ; we'll also need to adjust pandoc CSS in this case
- diaer(a) seems wrong (accent too high)
- the headings lose boldface; is that right?  More generally: should the show rules for headings result in no h1? that seems wrong.  Better to change in CSS via attributes?
- compare result with typst output
